#!/usr/bin/env node
/**
 * Set every plugin build version to the given semver and verify the shipped
 * launcher payload is intact.
 * Usage: node pin.mjs <version>
 * Does not prompt — caller must confirm before running.
 *
 * Hook commands carry no package version: `hooks.json` invokes the launcher at
 * a constant path, and runtime bumps ride `hook.mjs`. Only plugin manifests, the
 * payload `version` file, and the README's `npx … configure` examples name one.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../..");
const pkgRe = /@ev-ai\/agent-hook@\d+\.\d+\.\d+/g;
const semver = /^\d+\.\d+\.\d+$/;

const [, , version] = process.argv;
if (!semver.test(version || "")) {
  console.error("Usage: node pin.mjs <version>");
  process.exit(1);
}

const pin = `@ev-ai/agent-hook${version ? `@${version}` : ""}`;

const PLUGIN_DIRS = [
  "plugins/claude-runtime-hooks",
  "plugins/cursor-runtime-hooks",
  "plugins/codex-runtime-hooks",
];

const PLUGIN_MANIFESTS = [
  "plugins/claude-runtime-hooks/.claude-plugin/plugin.json",
  "plugins/cursor-runtime-hooks/.cursor-plugin/plugin.json",
  "plugins/codex-runtime-hooks/.codex-plugin/plugin.json",
];

/** Generated by `sync:hooks` in the monorepo — must exist before a release. */
const PAYLOAD_FILES = ["hook.mjs", "launcher.sh", "launcher.ps1", "version"];

/** Release slugs the launcher can fetch a binary for. */
const PLATFORM_SLUGS = [
  "darwin-arm64",
  "darwin-x64",
  "linux-x64",
  "linux-arm64",
  "windows-x64",
  "windows-arm64",
];

const problems = [];
const notes = [];

for (const dir of PLUGIN_DIRS) {
  for (const file of PAYLOAD_FILES) {
    const rel = path.join(dir, file);
    if (!fs.existsSync(path.join(root, rel))) {
      problems.push(`Missing payload: ${rel} — run \`sync:hooks\` from the monorepo first`);
    }
  }

  // The launcher reads this file to pin its npx spec and its CDN path, so a
  // payload version that disagrees with the manifest ships a mismatched plugin.
  const versionRel = path.join(dir, "version");
  const versionAbs = path.join(root, versionRel);
  if (fs.existsSync(versionAbs)) {
    const shipped = fs.readFileSync(versionAbs, "utf8").trim();
    if (shipped !== version) {
      problems.push(
        `${versionRel} says ${shipped}, not ${version} — re-run \`sync:hooks\` from a monorepo at ${version}`,
      );
    }
  }

  // Optional: only a release that cross-compiled the binaries ships checksums.
  const sumsRel = path.join(dir, "SHA256SUMS");
  const sumsAbs = path.join(root, sumsRel);
  if (!fs.existsSync(sumsAbs)) {
    notes.push(`No ${sumsRel} — the binary fetch will verify against the CDN copy instead`);
  } else {
    const listed = fs
      .readFileSync(sumsAbs, "utf8")
      .split("\n")
      .map((line) => line.trim().split(/\s+/)[1])
      .filter(Boolean);
    const missing = PLATFORM_SLUGS.filter(
      (slug) => !listed.some((entry) => entry.startsWith(`${slug}/`)),
    );
    if (missing.length > 0) {
      notes.push(`${sumsRel} covers ${listed.length}/6 platforms — missing ${missing.join(", ")}`);
    }
  }
  const hooksRel = path.join(dir, "hooks/hooks.json");
  const hooks = fs.readFileSync(path.join(root, hooksRel), "utf8");
  if (hooks.includes("npx")) {
    problems.push(`${hooksRel} still wires npx — run \`sync:hooks\` from the monorepo first`);
  }
  if (!hooks.includes("launcher.sh")) {
    problems.push(`${hooksRel} does not invoke launcher.sh`);
  }
}

if (problems.length > 0) {
  for (const problem of problems) {
    console.error(problem);
  }
  process.exit(1);
}

for (const note of notes) {
  console.log(`note: ${note}`);
}

let changed = 0;

for (const rel of PLUGIN_MANIFESTS) {
  const abs = path.join(root, rel);
  const json = JSON.parse(fs.readFileSync(abs, "utf8"));
  const old = json.version;
  json.version = version;
  fs.writeFileSync(abs, `${JSON.stringify(json, null, 2)}\n`);
  changed += 1;
  console.log(`updated ${rel}: ${old} → ${version}`);
}

// README only documents `npx … configure` / `migrate-to-plugin` — not hook commands.
const readmeAbs = path.join(root, "README.md");
const before = fs.readFileSync(readmeAbs, "utf8");
const after = before.replace(pkgRe, pin);
if (after === before) {
  console.log("Unchanged: README.md");
} else {
  fs.writeFileSync(readmeAbs, after);
  changed += 1;
  console.log("updated README.md");
}

console.log(`done: plugin version ${version}, payload verified (${changed} files)`);
