#!/usr/bin/env node
/**
 * Set every plugin build version to the given semver and verify the shipped
 * launcher payload is intact.
 * Usage: node pin.mjs <version>
 * Does not prompt — caller must confirm before running.
 *
 * Hook commands carry no package version: `hooks.json` invokes the launcher at
 * a constant path, and runtime bumps ride `hook.mjs`. Only plugin manifests and
 * the README's `npx … configure` examples name a version.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../..");
const pkgRe = /@ev-ai\/agent-hook@\d+\.\d+\.\d+/g;
const semver = /^\d+\.\d+\.\d+$/;

const [, , version] = process.argv;
if (!semver.test(version || "")) {
  console.error("Usage: node pin.mjs <version>");
  process.exit(1);
}

const pin = `@ev-ai/agent-hook${version ? `@${version}` : ""}`;

const PLUGIN_DIRS = [
  "plugins/claude-runtime-hooks",
  "plugins/cursor-runtime-hooks",
  "plugins/codex-runtime-hooks",
];

const PLUGIN_MANIFESTS = [
  "plugins/claude-runtime-hooks/.claude-plugin/plugin.json",
  "plugins/cursor-runtime-hooks/.cursor-plugin/plugin.json",
  "plugins/codex-runtime-hooks/.codex-plugin/plugin.json",
];

/** Generated by `sync:hooks` in the monorepo — must exist before a release. */
const PAYLOAD_FILES = ["hook.mjs", "launcher.sh", "launcher.ps1"];

const problems = [];

for (const dir of PLUGIN_DIRS) {
  for (const file of PAYLOAD_FILES) {
    const rel = path.join(dir, file);
    if (!fs.existsSync(path.join(root, rel))) {
      problems.push(`Missing payload: ${rel} — run \`sync:hooks\` from the monorepo first`);
    }
  }
  const hooksRel = path.join(dir, "hooks/hooks.json");
  const hooks = fs.readFileSync(path.join(root, hooksRel), "utf8");
  if (hooks.includes("npx")) {
    problems.push(`${hooksRel} still wires npx — run \`sync:hooks\` from the monorepo first`);
  }
  if (!hooks.includes("launcher.sh")) {
    problems.push(`${hooksRel} does not invoke launcher.sh`);
  }
}

if (problems.length > 0) {
  for (const problem of problems) {
    console.error(problem);
  }
  process.exit(1);
}

let changed = 0;

for (const rel of PLUGIN_MANIFESTS) {
  const abs = path.join(root, rel);
  const json = JSON.parse(fs.readFileSync(abs, "utf8"));
  const old = json.version;
  json.version = version;
  fs.writeFileSync(abs, `${JSON.stringify(json, null, 2)}\n`);
  changed += 1;
  console.log(`updated ${rel}: ${old} → ${version}`);
}

// README only documents `npx … configure` / `migrate-to-plugin` — not hook commands.
const readmeAbs = path.join(root, "README.md");
const before = fs.readFileSync(readmeAbs, "utf8");
const after = before.replace(pkgRe, pin);
if (after === before) {
  console.log("Unchanged: README.md");
} else {
  fs.writeFileSync(readmeAbs, after);
  changed += 1;
  console.log("updated README.md");
}

console.log(`done: plugin version ${version}, payload verified (${changed} files)`);
